### ISSUE TITLE
Issue on page /prevention/simplesolutions.html

### ISSUE THREAD

**Issue by LogicBypass** [nocomplexity/SecurityArchitecture#6]
Dead link at [Respond Section](https://github.com/nocomplexity/SecurityArchitecture/blob/master/prevention/simplesolutions.md#respond):

### Respond
>:class: tip, dropdown
>Do not reinvent the wheel. For every simple or complex security incident a good procedure is already invented. 
>So just do:
>* Use and reuse existing security incident procedures. 
>`A good collection can be found here [link]`

**Comment by nocomplexity** [comment]
Many thanks for reporting this issue!
Dead link corrected now. 
Regards!

**Comment by nocomplexity** [comment]
Updated.
